### ISSUE TITLE
Make font host configurable

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/pattern-library#39]
# Description
Currently, the pattern library is hard-coded to look on openstax.org for its font files. It could be set up to look on the current host, but that does not work for Accounts.
What we need is a macro instead of a hard-coded file (ideally with a default of openstax.org). Then it can be whatever the user needs it to be.

# Acceptance criteria
Font host is configurable on the build system using the pattern library.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
