### ISSUE TITLE
Filtering multiple select widget

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/pattern-library#41]
# Description
Per discussion in business-intel-dev: https://openstax.slack.com/archives/C6NRD0CCQ/p1585865716304300

### Hi-fi designs:
Initial: https://projects.invisionapp.com/share/JWWZILWXN7H#/screens
With item selected: https://projects.invisionapp.com/share/STWR0808GXF#/screens

Will provide more description after discussion with @steveburkett 
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/9472c8a7-5f61-41e5-aa8c-990cf1d3db1d)

## Important Note
This request is for a functional widget, for use in any OpenStax product. That means it needs to be embeddable in different sytems (Rails, React, maybe Nuxt), which means it should not be written in any framework. To that end, I am investigating SvelteJS, which compiles down to plain JavaScript. The widget itself is not very difficult, but figuring out the technology to make it cross-platform embeddable will take some time.

*Update:* I ultimately was able to build an embeddable widget in SvelteJS, but the bundled size of it was nearly the size of the Knockout framework. I opted to use Knockout instead. It is easy to plug into Rails.

## Testing harness
Steve made a simple Rails app for trying it out:
https://github.com/steveburkett/railsplugintest

## To do
- [x] Create the widget within the test harness
- [x] Put the widget in a separate package
- [x] Use the package in the test harness, instead of a local version
- [x] Add styling to the Pattern Library
- [x] Apply PL styling to the instance in the harness

**Comment by RoyEJohnson** [comment]
They can search for things by group (say, Math) or particular titles.
Selected items accumulate as boxes in the typing area.
There are two modes: presenting rows of boxes for selection vs just a stack that filters based on what you type, in addition to having grouped stuff vs. not having groups.m

**Comment by RoyEJohnson** [comment]
Moving back to Design Done for now. When Accounts is ready to finalize, we'll make sure it's got everything they need. Right now, there's an open branch in pattern-library that will become a PR.

**Comment by BryanEliDimas** [comment]
I have not yet had the chance to confirm if the new version of the gem automagically got updated or if there's something left to do in order for that to happen. Btw.

**Comment by BryanEliDimas** [comment]
@brittanyearly You have already been testing this indirectly when test step 4. The book selections.
