### ISSUE TITLE
Change radio button pip color

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/pattern-library#67]
# Description
Part of #2047 was to change the color of selected radio buttons to match checkbox selected color.

# Acceptance test
The adoption form uses a radio group if you enter an unknown school name. The new color is as depicted.
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/4dead6bb-7a8c-4ef8-a9bd-02a0f87592fa)

**Comment by brittanyearly** [comment]
Unable to test Adoption in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
